GoProWebApp/GoProWebApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("controller/", include("controller.urls")),
    path('admin/', admin.site.urls),
]

GoProWebApp/controller/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path

from . import views

app_name = "controller"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:timelapse_id>/", views.detail, name="detail"),
    path("gopro/start/<str:gopro_id>/", views.gopro_start, name="gopro_start"),
    path("gopro/stop/<str:gopro_id>/", views.gopro_stop, name="gopro_stop"),
    # path("connect/", views.ConnectView.as_view(), name="connectview"),
    path("timelapse/start/", views.timelapse_start, name="timelapse_start"),
    path("timelapse/stop/", views.timelapse_stop, name="timelapse_stop"),
    path("connect/", views.connect, name="connect"),
    path("home/", views.HomeView.as_view(), name="home"),
    path("settings/", views.SettingsView.as_view(), name="settings"),
    path("admin/", views.AdminView.as_view(), name="admin")
]

GoProWebApp/controller/models.py
from pathlib import Path
from django.conf import settings
import asyncio, threading, requests

from threading import Thread, Event
from time import sleep
from requests.exceptions import RequestException
from django.db import models

from asgiref.sync import sync_to_async

from .thread_manager import ThreadManager

# Create your models here.
class Image(models.Model):
	date_time = models.DateTimeField(auto_now_add=True)
	path = models.FilePathField()
	name = models.CharField(max_length=20)
	size = models.FloatField(null=True)

class GoPro(models.Model):
	identifier = models.CharField(
		max_length=4,
		default='4933'
	)
	base_url = models.URLField(
		blank=True
	)
	connected = models.BooleanField(
		default=False, 
		blank=False
	)
	keep_alive_id = models.IntegerField(default=-1)
	keep_alive_signal = models.BooleanField(
		default=False,
		blank=False
	)

	def __str__(self):
		return self.identifier
	

	# TODO: feature on hold, linked to issue #28
	# @classmethod
	# def from_db(cls, db, field_names, values):
	# 	instance = super().from_db(db, field_names, values)
	# 	instance.restore()
	# 	return instance
	#
	# def restore(self):
	# 	if self.connected:
	# 		print("I was running at somepoint")
	# 		# TODO: call keep_alive, if returns ok then restore thread
	# 		self.connected = ThreadManager.check_thread(self.keep_alive_id)
	# 		self.save()
	# 		return
	# 	else:
	# 		print("I'm not running")

	def start(self): #TODO rename to [dis]connect
		if self.keep_alive_signal:
			print("Keep alive signal is already active, verifying thread")
			if ThreadManager.check_thread(self.keep_alive_id):
				print("thread verified as running")
				return
			print("Signal was active, but no thread was found")

		print(f"Starting keep alive signal for GoPro {self.identifier}")
		self.keep_alive_signal = True
		self.save()
		self.keep_alive_id = ThreadManager.start(self.keep_alive_id, self.keep_alive_task).ident
		self.save()

	def stop(self):
		if not self.keep_alive_signal:
			print("Keep alive signal is not active")
			return
		# Set the signal to send keep alive loop and stop attempting reconnect
		self.keep_alive_signal = False
		self.save()
		# if the thread is still running, then stop it
		ThreadManager.stop(self.keep_alive_id, self.keep_alive_task)
		self.keep_alive_id = -1
		self.save()
		print("Keep alive signal stopped")

	def keep_alive_task(self):
		url = self.base_url + "/gopro/camera/keep_alive"
		while self.keep_alive_signal:
			try:
				if not self.connected: 
					print("not connected")
					self.connect()
				# print(f"running {self.identifier} {self.base_url}")
				requests.get(url, timeout=2) #TODO refactor outside of function
			except RequestException:
				print("Failed to communicate with GoPro")
				self.connected = False
				self.save()
			sleep(3)
			# await self.arefresh_from_db() # TODO this resets self.connect to False, I thought it would update to the most recent value

		if not self.keep_alive_signal: 
			print("Keep alive signal caused stoppage")

	def connect(self):
		if not self.base_url:
			self.generate_base_url()
		while not self.connected and self.keep_alive_signal:
			try:
				print("trying connection")
				response = self.enable_usb_control()
				if response.ok:
					print("Connected via USB")
					self.connected = True
					self.save()
					return
			except requests.Timeout as e:
				print("Failed to enable wired control. Retrying wakeup")

			try:
				print("Attempting wake up via BLE")
				# TODO await ble_connect.connect_ble(self.identifier)

			except RuntimeError as e:
				print(f"Error connecting via BLE")

			print("Waiting for camera")
			sleep(10)
			# await self.arefresh_from_db()
		print("connected")

	def enable_usb_control(self):
		return requests.get(f"{self.base_url}/gopro/camera/control/wired_usb?p=1", timeout=2)

	def is_alive(self) -> bool:
		return self.get_thread().is_alive()
	
	def generate_base_url(self) -> str:
		base_url = f"http://172.2{self.identifier[1]}.1{self.identifier[2]}{self.identifier[3]}.51:8080"
		self.base_url = base_url
		self.save()
		return base_url

	def is_connected(self) -> bool:
		return self.connected
	
	def enable_photo_mode(self) -> bool:
		timelapse_preset_url = self.base_url + '/gopro/camera/presets/load?id=65536'
		return requests.get(timelapse_preset_url, timeout=2).ok
	
	def get_status(self) -> dict:
		try:
			status = {}
			response_json = requests.get(self.base_url + "/gopro/camera/state", timeout=2).json()
			status['battery'] = response_json['status']['2']
			status['photos_remain'] = response_json['status']['34']
			status['photos_taken'] = response_json['status']['38']
			status['free_space_kb'] = response_json['status']['54']
			return status

		except RequestException as e:
			print("Failed to get status")
	
	def start_shutter(self) -> int:
		try:
			response = requests.get(self.base_url + "/gopro/camera/shutter/start", timeout=2)
			print("Shutter")
			sleep(1)  # wait for camera to finish
			return response.status_code
		
		except RequestException as e:
			print("Failed to start shutter")

	def download_latest(self, delete) -> str:
		# Determine folder and name of latest media
		response = requests.get(self.base_url + '/gopro/media/list', timeout=2)
		response_json = response.json()
		if response.ok:
			print("download_latest response", response.status_code)
			latest_img_dir = response_json['media'][-1]['d']
			latest_img_name = response_json['media'][-1]['fs'][-1]['n']

			# Start single file download
			self.download_media(latest_img_dir, latest_img_name)

			if delete:
				self.delete_media(latest_img_dir, latest_img_name)

		else:
			print("could not get media list")
		
		# return dest_path / latest_img_dir / latest_img_name
	
	def download_media(self, srcfolder, srcimage):
		# Target URL
		url = self.base_url + f"/videos/DCIM/{srcfolder}/{srcimage}"
		# Path file will be saved in
		path = (Path(__file__).parent / "static/controller/images").resolve()

		try:
			#Download Image
			with requests.get(url, timeout=2, stream=True) as response:
				print("download_media response", response.status_code)
				response.raise_for_status()
				with open(f"{path}/{srcimage}", 'wb') as f:
					f.write(response.content)

			# Store image reference in db
			image = Image(path=path, name=srcimage)
			image.save()

		except requests.exceptions.RequestException as e:
			print("error")

	def delete_media(self, srcfolder, srcimage):
		url = self.base_url + f"/gopro/media/delete/file?path={srcfolder}/{srcimage}"
		response = requests.get(url, timeout=2)
		print("delete_media response", response.status_code)

	def set_auto_powerdown_off(self) -> int:
		try:
			OPTIONS = "setting=59&option=0"
			response = requests.get(self.base_url + "/gopro/camera/setting" + "?" + OPTIONS, timeout=2)
			return response.status_code
		except RequestException as e:
			print("Failed to turn auto powerdown off")

	def set_auto_powerdown_on(self) -> int:
		try:
			url = self.base_url + "/gopro/camera/setting?setting=59&option=4"
			response = requests.get(url, timeout=2)
			return response.status_code
		except RequestException as e:
			print("Failed to turn autopower down on")


class Timelapse(models.Model):
	gopro = models.OneToOneField(GoPro, on_delete=models.PROTECT)
	interval = models.PositiveIntegerField(default=10)
	photos_taken = models.PositiveIntegerField(default=0)
	timelapse_preset_url = models.CharField(
		default="/gopro/camera/presets/load?id=65536", editable=False, max_length=40
	)
	
	task_id = models.IntegerField(default=-1)  # Timelapse thread id
	task_signal = models.BooleanField(default=False, blank=False) # True if timelapse task is active

	def __str__(self):
		return str(self.interval)
	
	def start(self):
		if self.task_signal:
			print(f"Timelapse task already running on {self.gopro.identifier}")
			return
		
		if self.gopro.enable_photo_mode():
			print(f"Starting timelapse task for {self.gopro.identifier}")

			self.task_signal = True
			self.save(update_fields=["task_signal"],force_update=True)
			self.refresh_from_db()
			self.task_id = ThreadManager.start(thread_id=self.task_id, thread_target=self.timelapse_task).ident
			self.save(update_fields=["task_id"])
			# print("Task signal set as: ", self.task_signal)
		else:
			print("Could not start timelapse as could not switch camera mode")

	def stop(self):
		if not self.task_signal:
			print(f"Timelapse task is not running")
			return

		self.task_signal = False
		self.save(force_update=True)
		ThreadManager.stop(thread_id=self.task_id, thread_target=self.timelapse_task)

		self.task_id = -1
		self.save(force_update=True)
		print("Timelapse task stopped")


	def timelapse_task(self):
		print("New timelapse task started")
		self.refresh_from_db()
		while self.task_signal:
			try:
				if self.gopro.start_shutter() == 200:
					self.photos_taken += 1
					self.gopro.download_latest(delete=True)	
					self.save()
					sleep(self.interval)
				else:
					print("error, photot not taken")
			except RequestException as e:
				print("Picture not taken")
				print(e)
			
			self.refresh_from_db()

		print("Timelapse task exiting")

GoProWebApp/controller/forms.py
from django import forms

from controller.models import GoPro


class ConnectForm(forms.ModelForm):
    class Meta:
        model = GoPro
        fields = ["identifier"]

GoProWebApp/controller/views.py
import asyncio

from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views import View
from django.views.generic.edit import FormView

import threading
from threading import Thread, Event
from time import sleep

from .models import *
from .forms import ConnectForm

TEMP_DIR = 'controller/'
GOPRO_ID = 4933

# Create your views here.


def index(request):
    timelapse_list = Timelapse.objects.all()
    return render(request, "controller/index.html", {"timelapse_list": timelapse_list})


def detail(request, timelapse_id):
    timelapse = get_object_or_404(Timelapse, pk=timelapse_id)
    return render(request, "controller/detail.html", {"item": timelapse})


def gopro_start(request):
    gopro = get_object_or_404(GoPro, identifier=GOPRO_ID)
    gopro.start()
    return HttpResponse("Started")


def gopro_stop(request):
    gopro = get_object_or_404(GoPro, identifier=GOPRO_ID)
    gopro.stop()
    return HttpResponse("Stopped")


def timelapse_start(request):
    timelapse = get_object_or_404(
        Timelapse, gopro=GoPro.objects.get(identifier=GOPRO_ID))
    timelapse.start()
    print("Timelapse started")
    return redirect('controller:home')

def timelapse_stop(request):
    timelapse = get_object_or_404(
        Timelapse, gopro=GoPro.objects.get(identifier=GOPRO_ID))
    timelapse.stop()
    print("Timelapse stopped")
    return redirect('controller:home')


def connect(request):
    gopro = get_object_or_404(GoPro, identifier=GOPRO_ID)
    gopro.start()
    print("Connecting")
    return redirect('controller:home')


class HomeView(View):
    template_path = TEMP_DIR + 'home.html'

    def get(self, request):
        gopro = GoPro.objects.get(identifier=GOPRO_ID)
        status = gopro.get_status()
        timelapse = get_object_or_404(Timelapse, gopro=gopro)
        image_list = Image.objects.order_by("-date_time")[:20]

        timelapse_action = 'stop' if timelapse.task_signal else 'start'
        # image_list =
        return render(
					request, 
					self.template_path, 
					{
						"gopro": gopro, 
						"status": status, 
						"timelapse_action": timelapse_action,
            "image_list": image_list
					}
				)


class SettingsView(View):
    template_path = TEMP_DIR + "settings.html"

    def get(self, request):
        return render(request, self.template_path)


class AdminView(View):
    template_path = TEMP_DIR + "admin.html"

    def get(self, request):
        return render(request, self.template_path)

# Start/Stop
# class ConnectView(FormView):
#     template_name = "controller/connect.html"
#     form_class = ConnectForm

#     def form_valid(self, form):
#         identifier = form.cleaned_data['identifier']
#         gopro, created = GoPro.objects.get_or_create(identifier=identifier)
#         print(f"view alive? {gopro.is_alive()}")
#         if gopro.is_alive():
#             gopro.stop()
#             print(f"view alive after stopping? {gopro.is_alive()}")
#         else:
#             gopro.start()
#             print(f"view alive after starting? {gopro.is_alive()}")
#         return render(self.request, 'controller/detail.html', {'item': gopro})

    # def get(self, request):
    #     return render(request, self.template_name, {"form":self.form})

    # def post(self, request):
    #     form = ConnectForm(request.POST)
    #     print(form)
    #     if form.is_valid():
    #         gopro = GoPro.objects.get(identifier = form.cleaned_data["identifier"])
    #         t: Thread = GoProObj.get_keep_alive_thread(gopro.identifier)
    #         return HttpResponse(str(t.ident))

    #     return HttpResponse(form.errors)

GoProWebApp/controller/templates/controller/admin.html
{% extends "controller/base.html" %}

{% block admin_active %}
    active" aria-current="page
{% endblock admin_active %}

{% block heading %}
    Admin
{% endblock heading %}

{% block content %}
<div class="contrainer pxy-10">
    <p>Download media</p>
    <p>Clear SD Card</p>
    <p>Sync with cloud now</p>
    <p>Create new user</p>
</div>
{% endblock content %}

GoProWebApp/controller/templates/controller/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static 'favicons/favicon.ico' %}" type="image/x-icon">
    <title>{% block title %}GoProWebApp{% endblock title %}</title>
  </head>
  <body>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            </div>
        {% endfor %}
    {% endif %}
    <div class = "container py-3">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link {% block home_active %}{% endblock %}" href="{% url 'controller:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% block settings_active %}{% endblock %}" href="{% url 'controller:settings' %}">Settings</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% block admin_active %}{% endblock %}" href="{% url 'controller:admin' %}">Admin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
        </nav>
        <div class="container p-3">
            {% block content%}
            {% endblock %}
        </div>
        
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

GoProWebApp/controller/templates/controller/connect.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Connect</title>
</head>
<body>
    <form action="{% url 'controller:connect' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if  %}{% endif %}
        <input type="submit" value="Connect">
    </form>
</body>
</html>

GoProWebApp/controller/templates/controller/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detail</title>
</head>
<body>
    {{ item }}
</body>
</html>

GoProWebApp/controller/templates/controller/home.html
{% extends "controller/base.html" %}
{% load static %}

{% block home_active %}
    active" aria-current="page
{% endblock home_active %}


{% block heading %}
    Home
{% endblock heading %}

{% block content %}
    <div class="row">
        <div class="col-sm">
            {% if image_list %}
            <img src=" {% static 'controller/images/'|add:image_list.0.name %}" class="img-fluid" alt="">
            {% else %}
                <img src="{% static 'controller/GOPR4764.JPG'%}" class="img-fluid" alt="">
            {% endif %}
        </div>
        <div class="col-sm">
            {% if gopro.connected %}
                <p><b>Connected</b> <i></i></p>
                <p>battery: {{ status.battery }}</p>
                <br>
                <p>photos taken {{ status.photos_taken }}</p>
                <br>
                <p>etc...</p>
                <form id="timelapseActionForm" action="{% url "controller:timelapse_"|add:timelapse_action %}" method="post">
									{% csrf_token %}
									<button class="btn btn-primary btn-sm" id="timelapseActionButton" type="submit">
										<span class="timelapse-button-text">{{ timelapse_action|capfirst }}</span>
										<span class="spinner-border spinner-border-sm d-none" aria-hidden="true"></span>
									</button>
                </form>
            {% else %}
                <p>Not Connected:</p>
                <form id = "connectForm" action="{% url 'controller:connect' %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-primary btn-sm" id="submitButton" type="submit">
                        <span class="button-text">Connect</span>
                        <span class="spinner-border spinner-border-sm d-none" aria-hidden="true"></span>
                    </button>
                </form>
            {% endif %}
        </div>
    </div>
    <table class="table table-hover">
        <tr>
            <th>Capture date</th><th>Name</th><th>Size (b)</th>
        </tr>
        {% if image_list %}
            {% for image in image_list %}
                <tr>
                    <td>{{ image.date_time | date:"G:i:s d-m-Y"}}</td>
                    <td>{{ image.name }}</td>
                    {% comment %} <td>{{ image.path }}</td> {% endcomment %}
                    <td>{{ image.size }}</td>
                </tr>
            {% endfor %}
        {% else %}
            <h3>Taken picture will appear here</h3>
            <p>Start taking pictures to begin</p>
        {% endif %}
    </table>

    <script>
			{% if gopro.connected is False %}
				document.getElementById("connectForm").addEventListener("submit", function(){
					var submitButton = document.getElementById("submitButton");
					var buttonText = submitButton.querySelector("span.button-text");

					submitButton.querySelector("span.spinner-border").classList.remove("d-none");
					submitButton.querySelector("span.button-text").innerHTML = "Connecting...";
					submitButton.disabled = true;
				});
			{% endif %}
			document.getElementById("timelapseActionForm").addEventListener("submit", function(){
				var submitButton = document.getElementById("timelapseActionButton");
				var buttonText = submitButton.querySelector("span.timelapse-button-text");

				if (buttonText.innerHTML.trim() === "Stop") {
					submitButton.querySelector("span.spinner-border").classList.remove("d-none");
					buttonText.innerHTML = "Stopping...";
					submitButton.disabled = true;
				}
      });
    </script>
{% endblock content %}

GoProWebApp/controller/templates/controller/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
</head>
<body>
    {% if timelapse_list %}
        <ul>
            {% for item in timelapse_list %}
                <li>{{ item.gopro }}</li>
                <li>{{ item.interval }}</li>
                <li>{{ item.photos_taken }}</li>
                <li>{{ item.thread_id }}</li>
                <br>
            {% endfor %}
        </ul>
    {% else %}
    {% endif %}
</body>
</html>

GoProWebApp/controller/templates/controller/settings.html
{% extends "controller/base.html" %}

{% block settings_active %}
    active" aria-current="page
{% endblock settings_active %}

{% block heading %}
    Settings
{% endblock heading %}

{% block content %}
<div class="contrainer pxy-10">
    <p>Timelapse Interval:</p>
    <p>Connected camera:</p>
    <p>Schedule:</p>
    <p>Sync with Google Cloud?</p>
</div>
{% endblock content %}